apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: solar-system 
  type: NodePort